### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Ksardas178/Java.-First-class#1]
1. Целое число - не самое удачное представление элемента доски. Их тоже (как и направления) следует представить перечислением. В отличие от направление, это отдельное публичное перечисление, которое будет являться частью API вашего класса.

2. `enum direction` -> `enum Direction`. Это тип, он должен называться с большой буквы.

3. Нужно ли отдельное поле size? Размер поля можно бесплатно получить из массива.

4. `equals`/`hashCode`/`toString` точно не будут лишними.

5. Нужно искать не только длину самой длинной последовательности, но и саму последовательность. (А длину как раз вычислить можно уже из неё). Предлагаю сделать отдельный класс, представляющий начало и конец последовательности (две целочисленные точки).

6. Тесты хотелось бы расширить.

**Comment by Ksardas178** [comment]
Вроде все дописано и работает
